### PR TITLE
rdkit-pypi replaced by rdkit on pypi

### PR DESCRIPTION
**Pull request by IAlibay**
Small thing, I believe rdkit now replaces rdkit-pypi for new releases.

### CODE REVIEW

**Comment by cbouy** [comment]
Right, thanks Irfan!

**Comment by IAlibay** [comment]
_might_ be using it as an excute to cycle CI a little bit ;)

**Comment by cbouy** [comment]
Looks like the CI pipeline needs some tweaking: conda-incubator/setup-miniconda#274 🤷‍♂️

**Comment by IAlibay** [comment]
I forgot about that issue 🤣 fix incoming

**Pull request merged**
