### PR TITLE
Update SMARTS for HBAcceptor and Ligand, fix issue #68

### PR DESCRIPTION
**Pull request by DrrDom**
I changed patterns for H-acceptor and Ligand as I suggested in https://github.com/chemosim-lab/ProLIF/issues/68
We may discuss them to make the final version

### CODE REVIEW

**Comment by cbouy** [comment]
@DrrDom I've made some very small changes to the HBond acceptor SMARTS, since from my understanding `!$(*(~a)~a)` is another non-standard way to specify non-aromatic atoms, which `O` already specifies (aliphatic oxygen), unless I'm missing something.

I've also added tests on SMARTS pattern matching so that what's supposed to pass and what's supposed to fail is a bit more clear, the relevant ones for HBonds are [here](https://github.com/chemosim-lab/ProLIF/pull/73/files#diff-82a28777fddc092b12eb4cb22999abdaef5170c10f27b47e13c9e9c7d547b241R152-R167).

I'll try to merge this week as it's a great improvement over the current behavior, and we can further discuss other interaction SMARTS in a new PR if needed.

**Comment by DrrDom** [comment]
I suggest to make other changes related to ionic features, both positive and negative, and include them in this PR.
The issue - not recognized delocalization of charges that miss some ionic interactions.

For negative features these are carboxylic, sulfonic and phosphate groups. Oxygen without an explicit charge is not recognized as a center of a negative charge. This can be encoded in a generic way, I hope. Here is an extended pattern - `"[-{1-},$(O=[*]-[O-])]"`

For positive features these are amidine and guanidine groups. It may be a little bit tricky. The basic suggestion is `"[+{1-},$([NH2]-[*]=[NH2+])]"`. It does not take into account substitution of nitrogens. So a more general pattern may be `"[+{1-},$([NX3]-[*]=[NX3+])]"`. I'm not sure that the second pattern is good, because it should match groups like `[CH3][CH](=[NH2+])[NH][OH]` where NH near oxygen would not delocalize the charge efficiently. To improve it we can construct this pattern `[+{1-},$([NX3]-[*]=[NX3+])&!$([NX3](-O)-[*]=[NX3+])]`, which excludes this counter example. I think this would be reasonable. In future other counterexamples can be excluded if needed.

I did not test all these patterns, but they should be valid.

**Comment by DrrDom** [comment]
This pattern `!$(*(~a)~a)` designates an atom not connected to two aromatic atoms, the atom itself may be not aromatic, e.g. Ph-O-Ph.

**Comment by cbouy** [comment]
My bad, I mistook `~` with `:`, thanks for the clarification.

Yes, agreed. Until I find the time to implement RDKit's resonance structure enumeration for pattern matching this seems like a good workaround.

For the amidine and guanidine, I would have said `[+{1-},$([NX3&!$([NX3]-O)]-[*]=[NX3+])]`. Do we need the `[*]` in there or can we just specify `[C]` ?

**Comment by DrrDom** [comment]
I agree with current patterns. Yes, we can use [C] in guanidine pattern. I have no further suggestions.

**Comment by cbouy** [comment]
Thanks a lot @DrrDom !

**Comment by DrrDom** [comment]
Thank you as well. Great work! We use this tool regularly.

**Pull request merged**
